name       : libcryptui
version    : 3.12.2
release    : 1
source     :
    - http://ftp.gnome.org/pub/gnome/sources/libcryptui/3.12/libcryptui-3.12.2.tar.xz : 71ead1a7b496f07f6c5102ae79945dd2515b7b9342c6edefe58b47318be20866
license    : 
    - GPL-2.0
    - GFDL-1.1
summary    : Libcryptui - Interface components for OpenPGP
description: |
    libcryptui is a library used for prompting for PGP keys. It's likely that this library will become deprecated in the near future.
builddeps  :
    - pkgconfig(sm)
    - pkgconfig(ice)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(gtk+-3.0)
    - gpgme
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
