name       : libcryptui
version    : 3.12.2
release    : 13
source     :
    - https://download.gnome.org/sources/libcryptui/3.12/libcryptui-3.12.2.tar.xz : 71ead1a7b496f07f6c5102ae79945dd2515b7b9342c6edefe58b47318be20866
license    :
    - GPL-2.0-only
    - GFDL-1.1
component  : system.utils
summary    : Libcryptui - Interface components for OpenPGP
description: |
    libcryptui is a library used for prompting for PGP keys. It's likely that this library will become deprecated in the near future.
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gpgme)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(ice)
    - pkgconfig(libassuan)
    - pkgconfig(libnotify)
    - pkgconfig(sm)
    - gtk-doc
    - gnupg
setup      : |
    %patch -p1 < $pkgfiles/allow-building-with-gnupg-2.2.patch
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
